version: 0.0
os: linux
files:
  - source: /home/ec2-user/app/deploy
    destination: /home/ec2-user/app/deploy/

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/stop.sh # nginx와 연결되지 않은 스프링 부트 종료.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh # nginx와 연결되어 있지 않은 포트로 스프링 부트 시작.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/health.sh # 새 서비스 health check.
      timeout: 600
      runas: ec2-user
