spring:
  datasource:
    url: jdbc:mysql://localhost:3306/simpleBoardDB?serverTimezone=Asia/Seoul
    username: simpleBoardAdmin
    password: hanseul369
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 593074685189-41dcdj82mjolgrrj05fgt833purdfatr.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
  thymeleaf:
    enabled: true

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

#logging:
#  file:
#    name: my-application.log
#    path: /path/to/log/file
#  level:
#    com.example.myapp: DEBUG

logging:
  level:
    org:
    springframework:
    jdbc:
    datasource: DEBUG